### ISSUE TITLE
ansible-vault requires either the cryptography library (preferred) or pycrypto in order to function

### ISSUE THREAD

**Issue by neverstew** [cytopia/docker-ansible#89]
Hello! We had an issue this morning in our build pipeline that looks like:

```
ansible-vault requires either the cryptography library (preferred) or pycrypto in order to function.
```

**Reproduction Steps**
Unfortunately, I can't do this justice because I can't re-build the image locally. Running `make build ANSIBLE=2.3 FLAVOUR=aws` fails with

```
 => ERROR [internal] load metadata for docker.io/cytopia/ansible-builder:latest                                                                        1.2s
------
 > [internal] load metadata for docker.io/cytopia/ansible-builder:latest:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
make: *** [build] Error 1
```

**Indicative Reproduction Steps**
Instead, here's what we're doing:

1. Specifying the `cytopia/ansible:latest-aws` as a base image for a CI job.
2. Running `ansible-playbook --vault-password-file ${VAULT_PASSWORD_FILE} -v <the playbook>`
3. Running this task as part of the playbook, where `vars/secret/staging.yml` is a vault
```
- name: Setup staging platform                                             
   block:                                                                     
    - name: Import environment config for staging                
       include_vars:                                                          
         file: vars/{{ item }}/staging.yml                                  
       loop:                                                                  
         - secret                                                             
         - platform                                                           
    - include_role:                                                          
       name: platform                                                        
```

Here's the error from the logs with a bit more context

```
TASK [Import environment config for staging] ***********************************
failed: [localhost] (item=secret) => {"ansible_facts": {}, "ansible_included_var_files": [], "ansible_loop_var": "item", "changed": false, "item": "secret", "message": "ansible-vault requires either the cryptography library (preferred) or pycrypto in order to function."}
```

**Notes**
This is [the place in ansible where this error is stemming from](https://github.com/ansible/ansible/blob/0f95371131cd41d97ad95c4e8bd983081eb29a2a/lib/ansible/parsing/vault/__init__.py#L37-L51). I've since installed their requirements and tested that it still works with 35.0.0.
